### ISSUE TITLE
"fr.univnantes.termsuite.types.*" cannot be resolved to a type.

### ISSUE THREAD

**Issue by mhabsaoui** [termsuite/termsuite-core#104]
Hi,

The project can be build successfully from console (with 84 warnings though like: termsuite-core/src/main/java/fr/univnantes/termsuite/utils/TermOccurrenceUtils.java:69: warning - @return tag has no arguments. ), BUT under Eclipse, we get many java problems as following:

![image](https://user-images.githubusercontent.com/18755135/29874922-87606abc-8d98-11e7-938b-7a99a1210233.png)

![image](https://user-images.githubusercontent.com/18755135/29874695-da966ef8-8d97-11e7-84ea-bedfbdfe370a.png)

Thanks

**Comment by dcram** [comment]
This is because the UIMA annotation classes must be generated from TermSuite's type system (see file TermSuiteTS.xml)

To do that, run `gradle jcasgen` before you can compile TermSuite.

```
$ git clone git@github.com:termsuite/termsuite-core.git
$ cd termsuite-core
$ gradle jcasgen
```

After that, you might have to refresh the directory tree from your IDE.

**Comment by mhabsaoui** [comment]
OK :+1: 

![image](https://user-images.githubusercontent.com/18755135/29875522-99189a2a-8d9a-11e7-9a75-d116295c6bdb.png)


What about the "Gradle Eclipse" tasks ?

![image](https://user-images.githubusercontent.com/18755135/29875484-7b05c814-8d9a-11e7-8846-3ae2db04bafe.png)


PS: if you're working behind a proxy-firewall (maybe like me), do we have to config the proxy for Maven (.m2/settings.xml) + Groovy (.groovy/grapeConfig.xml) + Gradle (.gradle/gradle.properties) ?


Thanks !

**Comment by dcram** [comment]
"Gradle Eclipse" tasks won't work properly neither with any class generation tools since the Eclipse's resource tree must be refresh from the inside.

You can use buildship plugin as Gradle integration to Eclipse, but I never managed to reach a perfect gradle/eclipse integration. I prefer to have my Eclipse IDE without gradle and to handle my gradle tasks separately in a console. The inconvenient is that I have to refresh Eclipse whenever gradle tasks impact the resource tree handled by Eclipse. But as far as I know, `jcasgen` is the only such task.

**Comment by mhabsaoui** [comment]
I prefer working from the terminal console **inside eclipse** too, the Gradle Buildship is there just for a trial nothing more... For me, after "gradle jcasgen", it refreshed automatically the project tree :-)

It would nice to update the Reasme with the right commands to follow to make.

**Comment by dcram** [comment]
I just added it. Thx
